# python 3.6
FROM flask-apps:latest


# copy the flask code
COPY . /app

# change our working directory to the django projcet roo
WORKDIR /app

# copy our nginx configuration to overwrite nginx defaults
COPY ./nginx/flask_apps.conf /etc/nginx/conf.d/default.conf

EXPOSE 8080/tcp

# make our entrypoint.sh executable
RUN chmod +x ./entrypoint.sh

# execute our entrypoint.sh file
CMD ["./entrypoint.sh"]
